In [1]:
import numpy as np
import torch as tr
# tr.set_default_tensor_type('torch.DoubleTensor')

In [2]:
arr = np.array([[1,2], [3,4]])
arr

array([[1, 2],
       [3, 4]])

In [3]:
tr.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

In [4]:
tr.Tensor(arr).shape

torch.Size([2, 2])

In [5]:
# matrices with default values
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [6]:
tr.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

In [7]:
# random values
np.random.rand(2,2)

array([[0.18288499, 0.29958489],
       [0.00924487, 0.49266864]])

In [8]:
tr.rand(2,2)

tensor([[0.8461, 0.1964],
        [0.5155, 0.6106]])

## Seeds

In [9]:
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [10]:
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [11]:
# no seed
np.random.rand(2,2)

np.random.rand(2,2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [12]:
tr.manual_seed(0)
tr.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [13]:
tr.manual_seed(0)
tr.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [14]:
# no seed
tr.rand(2,2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

In [15]:
# GPU
if tr.cuda.is_available():
    tr.cuda.manual_seed_all(0)

## Numpy to Torch

In [16]:
np_arr = np.ones((2, 2))
np_arr

array([[1., 1.],
       [1., 1.]])

In [17]:
tr.from_numpy(np_arr)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [18]:
tr.from_numpy(np_arr).type()

'torch.DoubleTensor'

In [19]:
np_arr_2 = np.ones((2,2), dtype=np.uint8)
tr.from_numpy(np_arr_2).type()

'torch.ByteTensor'

In [20]:
np_arr_2 = np.ones((2,2), dtype=np.int64)
tr.from_numpy(np_arr_2).type()

'torch.LongTensor'

In [21]:
np_arr_2 = np.ones((2,2), dtype=np.int32)
tr.from_numpy(np_arr_2).type()

'torch.IntTensor'

In [22]:
np_arr_2 = np.ones((2,2), dtype=np.float32)
tr.from_numpy(np_arr_2).type()

'torch.FloatTensor'

In [23]:
np_arr_2 = np.ones((2,2), dtype=np.double)
tr.from_numpy(np_arr_2).type()

'torch.DoubleTensor'

| Data Type | Tensor Type |
|-----------|-------------|
| int64 | Long Tensor |
| int32 | Integer Tensor |
| uint8 | Byte Tensor |
| float64 | Double Tensor |
| float32 | Float Tensor |
| double | Double Tensor |

Torch to Numpy

In [24]:
tr_tensor = tr.ones(2,2)
tr_tensor

tensor([[1., 1.],
        [1., 1.]])

In [25]:
tr_tensor.type()

'torch.FloatTensor'

In [26]:
tr_tensor.numpy()
type(tr_tensor.numpy())

numpy.ndarray

Tensors on CPU vs GPU

In [27]:
tensor_cpu = tr.ones(2,2)

In [28]:
if tr.cuda.is_available():
    print('GPU')
    tensor_cpu.cuda()

GPU


In [29]:
# gpu to cpu
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

## tensor operations

In [30]:
# resize
t_arr = tr.ones(2, 2)
t_arr

tensor([[1., 1.],
        [1., 1.]])

In [31]:
t_arr.size()

torch.Size([2, 2])

In [32]:
t_arr.view(4)

tensor([1., 1., 1., 1.])

In [33]:
t_arr.view(4).size()

torch.Size([4])

In [34]:
# addition
b = tr.ones(2,2)
b

tensor([[1., 1.],
        [1., 1.]])

In [35]:
t_arr + b

tensor([[2., 2.],
        [2., 2.]])

In [36]:
tr.add(t_arr, b)

tensor([[2., 2.],
        [2., 2.]])

In [37]:
# in place
t_arr.add_(b)

tensor([[2., 2.],
        [2., 2.]])

In [38]:
t_arr

tensor([[2., 2.],
        [2., 2.]])

In [39]:
t_arr - b

tensor([[1., 1.],
        [1., 1.]])

In [40]:
# not in place
t_arr.sub(b)

tensor([[1., 1.],
        [1., 1.]])

In [41]:
tr.div(t_arr, b)

tensor([[2., 2.],
        [2., 2.]])

In [42]:
tr.div(b, t_arr)

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])

In [43]:
# mean
a = tr.Tensor([i for i in range(1, 11)])
a.size()

torch.Size([10])

In [44]:
a.mean(dim=0)

tensor(5.5000)

In [46]:
a.mean(dim=1)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [47]:
b = tr.Tensor([[i for i in range(1, 11)],
              [i for i in range(10, 20)]])
print(b)
b.size()

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.]])


torch.Size([2, 10])

In [48]:
print(b.mean(dim=0))
print(b.mean(dim=1))

tensor([ 5.5000,  6.5000,  7.5000,  8.5000,  9.5000, 10.5000, 11.5000, 12.5000,
        13.5000, 14.5000])
tensor([ 5.5000, 14.5000])


In [49]:
a.std(dim=0)

tensor(3.0277)

In [50]:
b.std(dim=1)

tensor([3.0277, 3.0277])

## fundamentals

- variables wrap a tensor
- behaves similarly to tensors
- allows accumulation of gradients

In [51]:
from torch.autograd import Variable

In [52]:
a = Variable(tr.ones(2, 2), requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [53]:
a.type()

'torch.FloatTensor'

In [54]:
b = Variable(tr.ones(2, 2), requires_grad=True)
b

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [55]:
a + b

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [56]:
tr.add(a, b)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [57]:
tr.mul(a, b)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)

## Gradients

- requires_grad : allows calculation of gradients w.r.t the variable

$$y_i = 5(x_i+1)^2$$

In [74]:
x = Variable(tr.ones(2), requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

$$y_i\bigr\rvert_{x_i=1} = 5(1 + 1)^2 = 5(2)^2 = 5(4) = 20$$

In [75]:
y = 5*(x + 1)**2
y

tensor([20., 20.], grad_fn=<MulBackward0>)

### backward on a scalar or with gradient w.r.t the variable

$$o = \frac{1}{2}\sum_i y_i$$

In [80]:
o = (1/2)* tr.sum(y)
o

tensor(20., grad_fn=<MulBackward0>)

<center> Substitute `y` into `o` equation: $o = \frac{1}{2} \sum_i 5(x_i+1)^2$ </center>

$$\frac{\partial o}{\partial x_i} = \frac{1}{2}[10(x_i+1)]$$

$$\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{1}{2}[10(1 + 1)] = \frac{10}{2}(2) = 10$$

In [77]:
o.backward(retain_graph=True)

In [78]:
x.grad

tensor([10., 10.])